global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'nats'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['nats:8222']

  - job_name: 'sensors'
    static_configs:
      - targets: ['sensor-exporter:8000']
